wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.1
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.7.11
    session_history: code/_session_history.ipynb
    start_time: 1634186103
    t:
      1:
      - 1
      - 5
      2:
      - 1
      - 5
      3:
      - 2
      4: 3.7.11
      5: 0.12.1
      8:
      - 1
      - 5
